import os
ISEFlow_AIS_v1_0_0_path = os.path.join(os.path.dirname(__file__), 'ISEFlow/v1.0.0/ISEFlow_AIS_v1-0-0')
ISEFlow_GrIS_v1_0_0_path = os.path.join(os.path.dirname(__file__), 'ISEFlow/v1.0.0/ISEFlow_GrIS_v1-0-0')
ISEFlow_AIS_v1_1_0_path = os.path.join(os.path.dirname(__file__), 'ISEFlow/v1.1.0/ISEFlow_AIS_v1-1-0')
ISEFlow_GrIS_v1_1_0_path = os.path.join(os.path.dirname(__file__), 'ISEFlow/v1.1.0/ISEFlow_GrIS_v1-1-0')

import os
ISEFlow_AIS_v1_1_0_variables = ["year", "sector", "initial_year", "numerics_FD", "numerics_FE", "numerics_FE/FV", "stress_balance_HO", "stress_balance_Hybrid", "stress_balance_L1L2", "stress_balance_SIA_SSA", "stress_balance_SSA", "stress_balance_Stokes", "resolution_16", "resolution_20", "resolution_32", "resolution_4", "resolution_8", "resolution_variable", "init_method_DA", "init_method_DA_geom", "init_method_DA_relax", "init_method_Eq", "init_method_SP", "init_method_SP_icethickness", "melt_Floating_condition", "melt_No", "melt_Sub-grid", "ice_front_Div", "ice_front_Fix", "ice_front_MH", "ice_front_RO", "ice_front_StR", "open_melt_param_Lin", "open_melt_param_Nonlocal_Slope", "open_melt_param_PICO", "open_melt_param_PICOP", "open_melt_param_Plume", "open_melt_param_Quad", "standard_melt_param_Local", "standard_melt_param_Local_anom", "standard_melt_param_Nonlocal", "standard_melt_param_Nonlocal_anom", "Ocean forcing_Open", "Ocean forcing_Standard",
"Ocean sensitivity_High", "Ocean sensitivity_Low", "Ocean sensitivity_Medium", "Ocean sensitivity_PIGL", "Ice shelf fracture_False", "Ice shelf fracture_True", "pr_anomaly", "evspsbl_anomaly", "smb_anomaly", "ts_anomaly", "thermal_forcing", "salinity", "temperature", "pr_anomaly.lag1", "evspsbl_anomaly.lag1", "smb_anomaly.lag1", "ts_anomaly.lag1", "thermal_forcing.lag1", "salinity.lag1", "temperature.lag1", "pr_anomaly.lag2", "evspsbl_anomaly.lag2", "smb_anomaly.lag2", "ts_anomaly.lag2", "thermal_forcing.lag2", "salinity.lag2", "temperature.lag2", "pr_anomaly.lag3", "evspsbl_anomaly.lag3", "smb_anomaly.lag3", "ts_anomaly.lag3", "thermal_forcing.lag3", "salinity.lag3", "temperature.lag3", "pr_anomaly.lag4", "evspsbl_anomaly.lag4", "smb_anomaly.lag4", "ts_anomaly.lag4", "thermal_forcing.lag4", "salinity.lag4", "temperature.lag4", "pr_anomaly.lag5", "evspsbl_anomaly.lag5", "smb_anomaly.lag5", "ts_anomaly.lag5",
"thermal_forcing.lag5", "salinity.lag5", "temperature.lag5", "year", "sector", "initial_year", "numerics_FD", "numerics_FE", "numerics_FE/FV", "stress_balance_HO", "stress_balance_Hybrid", "stress_balance_L1L2", "stress_balance_SIA_SSA", "stress_balance_SSA", "stress_balance_Stokes", "resolution_16", "resolution_20", "resolution_32", "resolution_4", "resolution_8", "resolution_variable", "init_method_DA", "init_method_DA_geom", "init_method_DA_relax", "init_method_Eq", "init_method_SP", "init_method_SP_icethickness", "melt_Floating_condition", "melt_No", "melt_Sub-grid", "ice_front_Div", "ice_front_Fix", "ice_front_MH", "ice_front_RO", "ice_front_StR", "open_melt_param_Lin", "open_melt_param_Nonlocal_Slope", "open_melt_param_PICO", "open_melt_param_PICOP", "open_melt_param_Plume", "open_melt_param_Quad", "standard_melt_param_Local",
"standard_melt_param_Local_anom", "standard_melt_param_Nonlocal", "standard_melt_param_Nonlocal_anom", "Ocean forcing_Open", "Ocean forcing_Standard", "Ocean sensitivity_High", "Ocean sensitivity_Low", "Ocean sensitivity_Medium", "Ocean sensitivity_PIGL", "Ice shelf fracture_False", "Ice shelf fracture_True", "pr_anomaly", "evspsbl_anomaly", "smb_anomaly", "ts_anomaly", "thermal_forcing", "salinity", "temperature", "pr_anomaly.lag1", "evspsbl_anomaly.lag1", "smb_anomaly.lag1", "ts_anomaly.lag1", "thermal_forcing.lag1", "salinity.lag1", "temperature.lag1", "pr_anomaly.lag2", "evspsbl_anomaly.lag2", "smb_anomaly.lag2", "ts_anomaly.lag2", "thermal_forcing.lag2", "salinity.lag2", "temperature.lag2", "pr_anomaly.lag3", "evspsbl_anomaly.lag3", "smb_anomaly.lag3", "ts_anomaly.lag3", "thermal_forcing.lag3", "salinity.lag3", "temperature.lag3", "pr_anomaly.lag4", "evspsbl_anomaly.lag4", "smb_anomaly.lag4",
"ts_anomaly.lag4", "thermal_forcing.lag4", "salinity.lag4", "temperature.lag4", "pr_anomaly.lag5", "evspsbl_anomaly.lag5", "smb_anomaly.lag5", "ts_anomaly.lag5", "thermal_forcing.lag5", "salinity.lag5", "temperature.lag5",]

ISEFlow_AIS_v1_0_0_variables = columns = ['year', 'sector', 'pr_anomaly', 'evspsbl_anomaly', 'mrro_anomaly', 'smb_anomaly', 'ts_anomaly', 'thermal_forcing', 'salinity', 'temperature', 'pr_anomaly.lag1', 'evspsbl_anomaly.lag1', 'mrro_anomaly.lag1', 'smb_anomaly.lag1', 'ts_anomaly.lag1', 'thermal_forcing.lag1', 'salinity.lag1', 'temperature.lag1', 'pr_anomaly.lag2', 'evspsbl_anomaly.lag2', 'mrro_anomaly.lag2', 'smb_anomaly.lag2', 'ts_anomaly.lag2', 'thermal_forcing.lag2', 'salinity.lag2', 'temperature.lag2', 'pr_anomaly.lag3', 'evspsbl_anomaly.lag3', 'mrro_anomaly.lag3', 'smb_anomaly.lag3', 'ts_anomaly.lag3', 'thermal_forcing.lag3', 'salinity.lag3', 'temperature.lag3', 'pr_anomaly.lag4', 'evspsbl_anomaly.lag4', 'mrro_anomaly.lag4', 'smb_anomaly.lag4', 'ts_anomaly.lag4', 'thermal_forcing.lag4', 'salinity.lag4', 'temperature.lag4', 'pr_anomaly.lag5', 'evspsbl_anomaly.lag5', 'mrro_anomaly.lag5', 'smb_anomaly.lag5', 'ts_anomaly.lag5', 'thermal_forcing.lag5', 
                                          'salinity.lag5', 'temperature.lag5', 'initial_year', 'numerics_FD', 'numerics_FE', 'numerics_FE/FV', 'stress_balance_HO', 'stress_balance_Hybrid', 'stress_balance_L1L2', 'stress_balance_SIA_SSA', 'stress_balance_SSA', 'stress_balance_Stokes', 'resolution_16', 'resolution_20', 'resolution_32', 'resolution_4', 'resolution_8', 'resolution_variable', 'init_method_DA', 'init_method_DA_geom', 'init_method_DA_relax', 'init_method_Eq', 'init_method_SP', 'init_method_SP_icethickness', 'melt_Floating_condition', 'melt_No', 'melt_Sub-grid', 'ice_front_Div', 'ice_front_Fix', 'ice_front_MH', 'ice_front_RO', 'ice_front_StR', 'open_melt_param_Lin', 'open_melt_param_Nonlocal_Slope', 'open_melt_param_PICO', 'open_melt_param_PICOP', 'open_melt_param_Plume', 'open_melt_param_Quad', 'standard_melt_param_Local', 'standard_melt_param_Local_anom', 'standard_melt_param_Nonlocal', 'standard_melt_param_Nonlocal_anom', 'Ocean forcing_Open', 
                                          'Ocean forcing_Standard', 'Ocean sensitivity_High', 'Ocean sensitivity_Low', 'Ocean sensitivity_Medium', 'Ocean sensitivity_PIGL', 'Ice shelf fracture_False', 'Ice shelf fracture_True']



ISEFlow_GrIS_v1_0_0_variables = []
ISEFlow_GrIS_v1_1_0_variables = []