# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Install dependencies in order
python:
  install:
    - requirements: docs/readthedocs.requirements.txt  # Install HDF5 support first
    - requirements: requirements.txt  # Then install the rest
