[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ise"
version = "2.0.0"
authors = [
  { name="Peter Van Katwyk", email="pvankatwyk@gmail.com" },
]
description = "Package for creating ice sheet emulators predicting future sea level rise."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Brown-SciML/ise"