data:
  forcings: "/users/pvankatw/data/pvankatw/pvankatw-bfoxkemp/GHub-ISMIP6-Forcing/AIS/"
  output: "/users/pvankatw/data/pvankatw/pvankatw-bfoxkemp/GHub-ISMIP6-Forcing/AIS/Zenodo_Outputs/"
  export: "/users/pvankatw/data/pvankatw/pvankatw-bfoxkemp/processed_GHub-ISMIP6-Forcing/"
